services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - DB_URI=${DB_URI}
    volumes:
      - ./server:/app
      - /app/node_modules
